# Numpy
넘파이는 배열 데이터를 매우 빠르게 처리하기 위한 파이썬 외부 모듈이다  
넘파이는 C언어로 만든 바이너리 실행 기반으로써 대용량의 데이터를 빠르게 처리해야 할때 많이 사용되고, 현대의 데이터 분석, 인공지능 딥러닝 분야에서 많이 응용된다  

In [1]:
import numpy as np

li = [10, 20, 30, 40, 50]
print(li)

arr = np.array(li)  # numpy.ndarray
print(arr)
print(type(arr))

[10, 20, 30, 40, 50]
[10 20 30 40 50]
<class 'numpy.ndarray'>


In [2]:
# 여러가지 데이터 타입을 혼합하여 ndarray를 구성할 수 있으나, 이렇게 사용하지 말자!
li = [10, '10', '홍길동', True, None]
arr = np.array(li)
arr

array([10, '10', '홍길동', True, None], dtype=object)

In [3]:
# arange(n) : 0 ~ n-1개까지의 정수값을 배열로 만들어준다.
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
# ndarray.dtype : 배열의 아이템들을 대표할 수 있는 타입을 반환한다.
arr.dtype

dtype('int32')

In [5]:
# arange(start, end, step) : start ~ end-step까지 step씩 증가하는 값으로 배열을 구성해줌
arr = np.arange(0.1, 10, 0.1)
arr

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3,
       1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6,
       2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9,
       4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2,
       5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5,
       6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8,
       7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. , 9.1,
       9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [6]:
arr.dtype

dtype('float64')

In [7]:
# 인덱싱
print(arr[0])   # 배열의 첫번째 값
print(arr[-1])  # 배열의 마지막 값

0.1
9.9


In [8]:
#배열의 차원수

# shape: 차원수와 배열의 모양 정보를 구할 수 있다.

# 0차원 배열
arr = np.array(100)
print(f'{arr.ndim}차원') # 차원수를 알려줌
print(arr.shape)

# 1차원 배열
arr = np.array([10, 20, 30, 40, 50])    
print(f'{arr.ndim}차원') # 차원수를 알려줌
print(arr.shape) # 결과를 튜플형으로 반환해줌, 튜플의 길이가 차원수임.

# 2차원 배열
arr = np.array([[10, 20, 30, 40, 50], [10, 20, 30, 40, 50], [10, 20, 30, 40, 50]])
print(f'{arr.ndim}차원') # 차원수를 알려줌
print(arr.shape)

# 3차원 배열
arr = np.array([[[10, 20, 30, 40, 50], [10, 20, 30, 40, 50]],
                [[10, 20, 30, 40, 50], [10, 20, 30, 40, 50]]])
print(f'{arr.ndim}차원') # 차원수를 알려줌
print(arr.shape)

0차원
()
1차원
(5,)
2차원
(3, 5)
3차원
(2, 2, 5)


In [9]:
# list의 용도 : 데이터의 저장과 전달(전송)
li = [[1,2,3],[1,2,3,4,5,6,7,8],[1,2,3,4,5]] 

# ndarray의 용도 : 데이터 빠른 처리
# arr = np.array([[1,2,3,4,5],[1,2,3]])

In [10]:
# 2차원 배열
arr = np.array([[10, 20, 30, 40, 50], 
                [11, 21, 31, 41, 51], 
                [12, 22, 32, 42, 52]])

arr[2][1]
arr[2,1]    # 2차원 배열의 인덱싱

22

In [11]:
# 2차원 배열의 슬라이싱
arr[1,1:4]  # 행번호 1인덱스 행에서 1 ~ 4-1번 인덱스에 해당하는 값들을 취함

array([21, 31, 41])

In [12]:
# 2차원 배열의 슬라이싱
arr[:,2] # 모든행에서 인덱스 2번에 해당하는 값들을 취함

array([30, 31, 32])

In [13]:
# 2차원 배열의 슬라이싱 (많이 나옴!!!)
arr[:,2:]   # 모든 행에서 2번 인덱스 열부터 끝까지 취함, 결과는 2차원 배열이된다.

array([[30, 40, 50],
       [31, 41, 51],
       [32, 42, 52]])

## 데이터 타입
- i: integer, 정수형
- b: boolean, 논리형
- u: unsigned, 양의 정수형
- f: float, 실수형
- M: datetime, 날짜 시간형
- O: object
- S: string, 문자열형
- U: unicode, 유니코드 문자열형
- c: complex float, 복소수형
- m: timedelta, 시간차형

In [14]:
# 다양한 데이터 타입
# dtype을 지정하여 배열 생성하기
arr = np.array([1,2,3,4,5], dtype='S')  
arr

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [15]:
# dtype을 주지 않으면 기본적으로 Unicode형으로 저장됨
arr = np.array(['apple', 'tomato', 'grape'], dtype='U')
arr.dtype

dtype('<U6')

In [16]:
arr = np.array([100, 99, 88, 77, 50])  # 윈도우즈 64비트 시스템에서 기본 정수형 할당은 4바이트
arr.dtype

dtype('int32')

In [17]:
arr = np.array([100, 99, 88, 77, 50], dtype='i1')  # 바이트수 제한하기
arr.dtype

dtype('int8')

## Copy(복사본)과 View(참조)

In [18]:
# copy(복사본)
arr = np.arange(1, 11)
x = arr.copy()  # 카피를 생성한다.
print(arr)
print(x)    

arr[0] = 100
print(arr)
print(x)    # 원본의 값이 변경되어도 카피본은 변경되지 않는다.


[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[100   2   3   4   5   6   7   8   9  10]
[ 1  2  3  4  5  6  7  8  9 10]


In [19]:
# View(참조)
arr = np.arange(1, 11)
x = arr.view()  # 참조를 생성한다.
print(arr)
print(x)

arr[0] = 100    # 원본 배열의 값을 변경
print(arr)
print(x)        # 참조도 같이 바뀐다.

# 참조에서도 값을 변경할 수 있다.
x[-1] = 200
print(arr)      # 참조의 값을 바꾸면 원본도 값이 바뀐다!
print(x)       


[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[100   2   3   4   5   6   7   8   9  10]
[100   2   3   4   5   6   7   8   9  10]
[100   2   3   4   5   6   7   8   9 200]
[100   2   3   4   5   6   7   8   9 200]


In [20]:
arr = np.array([1,2,3,4,5])
x1 = arr.copy()
x2 = arr.view()

print(x1.base)  # x1은 복사본이기때문에 참조하는 값이 없다.
print(x2.base)  # x2가 참조하는 원본 배열을 보여준다.

None
[1 2 3 4 5]


In [21]:
# 모양 바꾸기(Reshape)

# 1 ~ 12까지의 값을 갖는 1차원 ndarray를 생성하세요, arange()이용하기
arr = np.arange(1, 13)
print(arr.shape)

# arr을 이용하여 4x3형태의 2차원 배열을 만듬
new_arr = arr.reshape(4, 3) 
print(new_arr)
print(arr)

# 아래와같이 데이터 개수가 일치하지 않으면 변경 불가!
# arr2 = arr.reshape(3,5)

# arr을 이용하여 3x2형태의 2차원 배열을 2개갖는 3차원 배열을 만듬
new_arr = arr.reshape(2, 3, 2) 
print(new_arr)
print(arr)

(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [22]:
# new_arr은 copy인가? view인가?
print(new_arr.base) # new_arr은 view이다!

new_arr[0] = 100
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[100 100 100 100 100 100   7   8   9  10  11  12]


In [23]:
# 데이터들의 순회
for n in arr:
    print(n, end=' ')

100 100 100 100 100 100 7 8 9 10 11 12 

In [24]:
print(new_arr.shape)

# 3차원 배열의 모양으로 출력하기
'''
100 100 
100 100 
100 100 

7 8
9 10
11 12
'''
for x in new_arr:   # x는 2차원 배열
    for y in x:     # y는 1차원 배열
        for n in y: # n은 y의 아이템
            print(n, end=' ')
        print()
    print('\n')



(2, 3, 2)
100 100 
100 100 
100 100 


7 8 
9 10 
11 12 




In [25]:
# numpy ndarray의 Iterator ===> nditer(): 몇 차원배열이든지 상관없이 모든 아이템들을 순회한다.
for n in np.nditer(new_arr):
    print(n, end=' ')

100 100 100 100 100 100 7 8 9 10 11 12 

## Numpy ndarray의 연산과 브로드캐스팅

In [26]:
# 배열 아이템들의 연산
arr = np.arange(1, 11)
print(arr)

# arr배열의 모든 아이템들을 10배하기
for i in range(10):
    arr[i] *= 10
print(arr)

# arr배열의 모든 아이템들을 10배하기
new_arr = arr * 10
print(new_arr)
print(new_arr.base) # new_arr이 복사본인지 View인지 체크하기

[ 1  2  3  4  5  6  7  8  9 10]
[ 10  20  30  40  50  60  70  80  90 100]
[ 100  200  300  400  500  600  700  800  900 1000]
None


In [27]:
x = new_arr * arr
print(x)

[  1000   4000   9000  16000  25000  36000  49000  64000  81000 100000]


In [28]:
# 2차원 배열의 브로드캐스팅
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr + 10) # 모든 아이템들에 10씩 더하기
print(arr*2)

x = np.array([10, 20, 30])
print(arr + x)

# 2차원 배열들끼리의 더하기
y = np.array([[100],
              [200]])
print(arr + y)


[[11 12 13]
 [14 15 16]]
[[ 2  4  6]
 [ 8 10 12]]
[[11 22 33]
 [14 25 36]]
[[101 102 103]
 [204 205 206]]


In [29]:
# 2차원 배열의 브로드캐스팅
arr1 = np.array([[1,2,3],
                [4,5,6]])

arr2 = np.array([[10,20,30],
                [40,50,60]])
print(arr1*arr2)

[[ 10  40  90]
 [160 250 360]]


In [30]:
# 행렬의 곱
arr1 = np.array([[1,2,3],
                [4,5,6]])

arr2 = np.array([[10,20],
                [30,40],
                [50,60]])
print(arr1@arr2)

[[220 280]
 [490 640]]


In [31]:
# 유용한 통계 함수들
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

print(f'전체합: {arr.sum()}')    # 전체 합
print(f'전체평균: {arr.mean()}')    # 전체 평균
print(f'{arr.sum(axis=0)}')     # 열방향 합
print(f'{arr.sum(axis=1)}')     # 한 행의 합
print(f'{arr.max(axis=1)}')     # 각 행의 최대값
print(f'{arr.mean(axis=1)}')    # 각 행의 평균
print(f'{arr.mean(axis=0)}')    # 각 열의 평균


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
전체합: 78
전체평균: 6.5
[15 18 21 24]
[10 26 42]
[ 4  8 12]
[ 2.5  6.5 10.5]
[5. 6. 7. 8.]


In [32]:
# 랜덤한 값으로 배열 생성하기 - 테스트 생성을 위하여 사용함

arr = (np.random.random(10) * 100).astype(int)
print(arr)


[83 38 10 55 54 61 75 68 99 40]


In [33]:
# 평균 60점을 기준으로 표준편차 10, 아이템들의 개수 10칸짜리 배열을 생성
arr = np.random.normal(60, 10, size=10).astype(int)
print(arr)

[56 69 50 63 76 62 46 58 42 55]


In [34]:
# 배열의 정렬
arr.sort()
print(arr)

[42 46 50 55 56 58 62 63 69 76]


In [35]:
# 배열의 Join
arr1 = np.random.normal(60, 10, size=10).astype(int)
arr2 = np.random.normal(60, 10, size=10).astype(int)
joined = np.concatenate((arr1, arr2))
joined

array([66, 46, 66, 51, 72, 76, 71, 63, 74, 56, 46, 57, 55, 80, 66, 52, 75,
       53, 54, 62])

In [36]:
# 2차원 배열의 concatenate
arr1 = np.random.normal(60, 10, size=10).astype(int).reshape(2,5)   # 2 x 5, 2차원 배열 생성
arr2 = np.random.normal(60, 10, size=10).astype(int).reshape(2,5)   # 2 x 5, 2차원 배열 생성
joined = np.concatenate((arr1, arr2), axis=0)
joined

array([[61, 59, 52, 44, 46],
       [58, 62, 40, 59, 58],
       [67, 39, 64, 49, 57],
       [38, 75, 40, 70, 53]])

In [37]:
# 2차원배열에 axis=1로하면 열방향 데이터들을 조인한다.
joined = np.concatenate((arr1, arr2), axis=1)
joined

array([[61, 59, 52, 44, 46, 67, 39, 64, 49, 57],
       [58, 62, 40, 59, 58, 38, 75, 40, 70, 53]])

In [38]:
# 데이터를 쌓기(join)
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1, arr2), axis=0)
print(arr)


[[1 2 3]
 [4 5 6]]


In [39]:
# 데이터를 쌓기(join), axis=1, 열방향으로 쌓아서 만들기
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [40]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [41]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [42]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1, arr2))   # concatenate(axis=0)와 결과가 같음
print(arr)

[1 2 3 4 5 6]


## Numpy배열에서 데이터 찾기

In [43]:
arr = np.array([1,2,3,4,5,4,4])
result = np.where(arr==4)
print(result)


(array([3, 5, 6], dtype=int64),)


In [44]:
arr = np.arange(1, 11)
result = np.where(arr % 2 == 0) # 값이 짝수인 아이템들만 찾기
print(result)

(array([1, 3, 5, 7, 9], dtype=int64),)


## Numpy에서 데이터 필터링

In [45]:
arr = np.array([10, 20, 30, 40, 50])
filters = [True, False, True, False, True]
result = arr[filters]
print(result)


[10 30 50]


In [46]:
# 클래식한 방식의 필터링
arr = np.arange(1, 11)
# 5이상의 값들만 필터링하기
filters = []
for n in arr:
    if n >= 5:
        filters.append(True)
    else:
        filters.append(False)
print(filters)      
# filtering
result = arr[filters]
print(result)


[False, False, False, False, True, True, True, True, True, True]
[ 5  6  7  8  9 10]


In [48]:
arr = np.arange(1, 11)
# 5이상의 값들만 필터링하기
# filters = arr >= 5  # 조건식(condition)을 filters라는 변수에 저장
result = arr[arr >= 5]

print(filters)
print(result)

[False False False False  True  True  True  True  True  True]
[ 5  6  7  8  9 10]


In [50]:
arr = np.array([5,12,19,21,7,3,40,10])
# 10이상 20이하인 값들만 추출하여 출력하기
result = arr[(arr>=10) & (arr<=20)] # and 대신 &을 사용
print(result)

[12 19 10]


In [55]:
# 
arr = np.random.normal(60, 10, size=12).reshape(4,3).astype(int)
print(arr)


[[50 55 66]
 [44 62 51]
 [60 50 71]
 [73 73 46]]


In [60]:
print(f'전체합: {arr.sum()}')
print(f'전체 평균: {arr.mean().round(2)}')      # .round(2): 소숫점 2자리까지만 만듬

print(f'한 행의 합: {arr.sum(axis=1)}')     # 각 행들의 합계를 구함, axis=1
print(f'한 행의 평균: {arr.mean(axis=1).round(2)}')     # 각 행들의 합계를 구함, axis=1

# 각 행의 평균이 60.0 이상인 행들만 필터링하기
filters = arr.mean(axis=1) > 60.0
result = arr[filters]
print(result)

전체합: 701
전체 평균: 58.42
한 행의 합: [171 157 181 192]
한 행의 평균: [57.   52.33 60.33 64.  ]
[[60 50 71]
 [73 73 46]]
