# NUMPY
- 배열을 빠르게 처리하도록 만들어진 파이썬 외부 라이브러리이다.
- 파이썬의 리스트와 매우 유사하지만 처리 속도가 빨라서, 데이터 분석에서 필수로 사용되는 모듈이다.

In [1]:
# numpy 모듈 추가하기
import numpy as np
print(f'Numpy Version: {np.__version__}')

Numpy Version: 2.4.3


## ndarray
N-dimension Array. 같은 타임의 데이터를 연속된 메모리 공간에 저장하는 컨테이너(배열)
- GPU 의 연산을 지원한다.

In [2]:
# ndarray 생성하기
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

# python list 생성하기
li = [1,2,3,4,5]
print(li, type(li))

[1 2 3 4 5] <class 'numpy.ndarray'>
[1, 2, 3, 4, 5] <class 'list'>


In [3]:
# 1차원 배열 생성하기
arr = np.array([1,2,3,4,5])
print(arr, arr.shape)

# 2차원 배열 생성하기
arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

# shape: 배열의 모양을 튜플의 형식으로 보여준다. 튜플의 아이템의 개수가 배열의 차원수 정보이고, 
# 숫자는 각 배열의 아이템들의 개수를 의미한다.

[1 2 3 4 5] (5,)
[[1 2 3]
 [4 5 6]] (2, 3)


In [4]:
# 0으로 초기화된 ndarray 생성, 매개변수로는 shape를 튜플의 형태로 전달한다.
arr_z = np.zeros((3,4))
print(arr_z, arr_z.shape)

# ones 메소드는 1로 초기화된 ndarray를 생성한다.
arr_one = np.ones((2,3,2))
print(arr_one, arr_one.shape)

# 10으로 초기화된 ndarray생성하기
arr_ten = np.full((3,2), 10)
print(arr_ten, arr_ten.shape)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4)
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]] (2, 3, 2)
[[10 10]
 [10 10]
 [10 10]] (3, 2)


In [5]:
# arange: 리스트의 range()함수와 비슷함
arr = np.arange(1, 10)  # start : end, start부터 end-1까지의 요소들로 배열을 생성함
print(arr)

arr = np.arange(1, 12, 2) # start : end : step
print(arr)

[1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11]


## dtype
Data Type
ndarray도 파이썬의 리스트와 마찬가지로 하나의 배열에 여러 종류의 데이터를 저장할 수 있지만, 일반적으로 그렇게 사용하지 않고, 하나의 데이터 타입으로 배열을 구성한다.

### numpy에서 다루는 데이터 타입
- i: integer(정수형)
- b: boolean(논리형)
- u: unsigned(부호가 없는 정수형 -> 양의 정수형)
- f: float(실수형)
- c: complex(복소수형)
- m: timedelta
- M: datetime(절대시간)
- O: object(파이썬의 최상위 클래스 타입)
- S: string(문자열)
- U: unicode(유니코드형 문자열)

In [6]:
li = [1, 3.14, '문자열']

arr = np.array(li)
print(arr, arr.dtype)

['1' '3.14' '문자열'] <U32


In [7]:
# 실수 64비트형으로 배열을 생성함
arr = np.array([1,2,3,4], dtype='float64')
print(arr, arr.dtype)

arr = np.array([1,2,3,4], dtype='float16')
print(arr, arr.dtype)


[1. 2. 3. 4.] float64
[1. 2. 3. 4.] float16


In [8]:
# 문자열 ndarray의 기본 데이터형은 unicode형이다.
# U나 S뒤에 오는 숫자는 글자수이다.
arr = np.array(['apple', 'samsung', 'tesla'])
print(arr, arr.dtype)

arr = np.array(['apple', 'samsung', 'tesla'], dtype='S')
print(arr, arr.dtype)

arr = np.array(['apple', 'samsung', 'tesla'], dtype='U')
print(arr, arr.dtype)


['apple' 'samsung' 'tesla'] <U7
[b'apple' b'samsung' b'tesla'] |S7
['apple' 'samsung' 'tesla'] <U7


In [9]:
# 강제로 실수형 데이터를 정수형으로 변환하여 ndarray를 생성
arr = np.array([1.1, 1.3, 1.5], dtype='int8')
print(arr, arr.dtype)

arr = np.array([1.1, 1.3, 1.5], dtype='float16')
print(arr, arr.dtype)

# astype('데이터 타입'): dtype을 이용하여 배열 원소들의 데이터 타입을 변환하여 새로운 배열을 생성
arr_i = arr.astype('int8')
print(arr_i, arr_i.dtype)


[1 1 1] int8
[1.1 1.3 1.5] float16
[1 1 1] int8


## 자주 사용되는 ndarray 속성
- shape: 배열의 모양, 차원수 정보
- ndim: 배열의 차원수
- size: 배열의 길이, 원소들이 개수
- dtype: 원소들의 타입
- nbytes: 메모리 용량(byte)

In [10]:
arr = np.arange(10)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.nbytes)

(10,)
1
10
int64
80


## 인덱싱과 슬라이싱


In [11]:
# 1차원 배열의 인덱싱과 슬라이싱
arr = np.arange(10)
print(f'배열의 첫번째 데이터: {arr[0]}')
print(f'배열의 마지막 데이터: {arr[-1]}')
print(f'배열의 다섯번째 데이터: {arr[4]}')

print(f'처음부터 5th 데이까지 자르기: {arr[:5]}')
print(f'두번째부터 5th 데이까지 자르기: {arr[1:5]}')
print(f'처음부터 끝까지 2스텝씩 자르기: {arr[::2]}')
print(f'배열 뒤집기: {arr[::-1]}')

배열의 첫번째 데이터: 0
배열의 마지막 데이터: 9
배열의 다섯번째 데이터: 4
처음부터 5th 데이까지 자르기: [0 1 2 3 4]
두번째부터 5th 데이까지 자르기: [1 2 3 4]
처음부터 끝까지 2스텝씩 자르기: [0 2 4 6 8]
배열 뒤집기: [9 8 7 6 5 4 3 2 1 0]


In [12]:
# 2차원 배열의 인덱싱과 슬라이싱
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr)

print(f'두번째 행의 두번째 열: {arr[1,1]}')
print(f'두번째 행의 두번째 열: {arr[-1,1]}')    # 마지막 행의 두번째 열 데이터와 같음
print(f'두번째 행의 네번째 열: {arr[-1,-1]}')
# 3가져와보기

print(arr[0, 1:])   # 첫번째 행의 두번째 아이템부터 끝까지
print(arr[:, 1])    # 전체 행을 대상으로 두번째 아이템들만 잘라내기
print(arr[:, 1:3])  # 전체 행을 대상으로 1번 인덱스의 원소부터 2번인덱스의 원소들까지 잘라내기

[[1 2 3 4]
 [5 6 7 8]]
두번째 행의 두번째 열: 6
두번째 행의 두번째 열: 6
두번째 행의 네번째 열: 8
[2 3 4]
[2 6]
[[2 3]
 [6 7]]


## 필터링하기
조건을 만족하는 원소들만 골라서 데이터를 가져올 수 있음

In [13]:
# 1 ~ 100까지의 난수들로 구성된 10칸짜리 배열 생성하기
np.random.seed(42)  # 랜덤한 값을 생성하는 규칙을 부여함
scores = np.random.randint(1, 101, 10).astype('float16')
print(scores)

# 80점 이상인 원소들만 필터링 하기
mask = scores >= 80 # masking 배열이 생성된다
print(mask, type(mask))

# masking 또는 filtering
print(scores[mask]) 
print(scores[scores >= 80])

# 복합조건 필터링하기
mask = (scores >= 50) & (scores < 70)
print(scores[mask])

# 20점 이하 점수는 0점으로 처리하기
scores[scores < 25] = np.nan    # 정수형 배열에는 NaN를 대입할 수 없음
print(scores)


[52. 93. 15. 72. 61. 21. 83. 87. 75. 75.]
[False  True False False False False  True  True False False] <class 'numpy.ndarray'>
[93. 83. 87.]
[93. 83. 87.]
[52. 61.]
[52. 93. nan 72. 61. nan 83. 87. 75. 75.]


In [14]:
# Fancy Indexing
idx = [1,3,5]
print(scores[idx])  # scores배열에서 1, 3, 5번 인덱스에 해당하는 값들을 필터링하여 가져옴

[93. 72. nan]


In [18]:
# reshape : 배열의 형태를 바꿈, 1차원 -> 2차원, 3차원 -> 1차원

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr, arr.shape)

newarr = arr.reshape(4,3)
print(newarr, newarr.shape)

newarr = arr.reshape(3,2,2)
print(newarr, newarr.shape)

# 아무때나 가능하지 않음
not_arr = arr.reshape(5,2)
print(not_arr, not_arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12] (12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]] (3, 2, 2)


ValueError: cannot reshape array of size 12 into shape (5,2)

In [22]:
# Flatting(평탄화): 다차원 배열을 1차원 배열로 변환
newarr = newarr.reshape(-1)
print(newarr, newarr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12] (12,)


In [ ]:
newarr = newarr.reshape(2,-1)   # 2 x 6, 2차원 배열로 만듬
print(newarr, newarr.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] (2, 6)


In [31]:
# 브로드캐스팅
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr * 5)
print(arr + 10)
print(arr - 2)
print(arr / 2)
print(arr // 2)
print(arr % 2)

[ 5 10 15 20 25 30 35 40 45 50 55 60]
[11 12 13 14 15 16 17 18 19 20 21 22]
[-1  0  1  2  3  4  5  6  7  8  9 10]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6. ]
[0 1 1 2 2 3 3 4 4 5 5 6]
[1 0 1 0 1 0 1 0 1 0 1 0]


In [ ]:
# 리스트
li = [1,2,3]
print(li * 5)   # 리스트를 5번씩 반복하여 새로운 리스트를 생성
print(li + 10)  # 안되는 연산

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


TypeError: can only concatenate list (not "int") to list

In [34]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])
print(arr1 + arr2)
print(arr2 - arr1)
print(arr1 * arr2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]


In [36]:
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

arr2 = np.array([10, 20, 30])

print(arr1 + arr2)
print(arr1 * arr2)


[[11 22 33]
 [14 25 36]
 [17 28 39]]
[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


In [ ]:
# shape가 맞아야 연산이 가능하다
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

arr2 = np.array([10, 20, 30, 40])
print(arr1 + arr2)

ValueError: operands could not be broadcast together with shapes (3,3) (4,) 